-- Goal Execution App: create the nine tables.
--
-- Run this ONCE, in the Supabase SQL Editor, in the project called Goal Bot.
--
-- What it does: creates nine empty tables and locks every one of them so that
-- only server-side code holding the private key can read or write. It adds no
-- content of your own. Your trading rules, checklist and settings go in
-- separately, in 002-seed-content.sql, so that this file can be re-run safely
-- and never touches your words.
--
-- Safe to run twice: every statement says "if not exists", so a second run
-- changes nothing rather than failing or duplicating.

begin;

-- ---------------------------------------------------------------- settings

-- A simple list of name-and-value pairs. Holds telegram_chat_id.
create table if not exists public.app_settings (
  key         text primary key,
  value       text,
  updated_at  timestamptz not null default now()
);

-- ------------------------------------------------------------------- goals

create table if not exists public.goals (
  id           bigint generated by default as identity primary key,
  title        text not null,
  detail       text,
  is_ultimate  boolean not null default false,
  sort_order   integer not null default 0,
  created_at   timestamptz not null default now()
);

-- ---------------------------------------------------------------- projects

create table if not exists public.projects (
  id          bigint generated by default as identity primary key,
  name        text not null,
  goal_id     bigint references public.goals(id) on delete set null,
  is_active   boolean not null default true,
  sort_order  integer not null default 0,
  created_at  timestamptz not null default now()
);

-- ----------------------------------------------------------- roadmap steps

create table if not exists public.roadmap_steps (
  id          bigint generated by default as identity primary key,
  project_id  bigint not null references public.projects(id) on delete cascade,
  sort_order  integer not null,
  title       text not null,
  detail      text,
  status      text not null default 'not_started'
              check (status in ('not_started', 'current', 'complete', 'skipped')),
  created_at  timestamptz not null default now()
);

-- Your rule is that exactly one step per project is the current one. This makes
-- the database itself refuse a second, rather than trusting every future piece
-- of code to remember. A rule nothing enforces is a rule that gets broken.
create unique index if not exists roadmap_one_current_step_per_project
  on public.roadmap_steps (project_id)
  where status = 'current';

-- ----------------------------------------------------------- trading rules

-- Your six rules. Read out word for word, never reworded or reordered.
create table if not exists public.trading_rules (
  id          bigint generated by default as identity primary key,
  sort_order  integer not null,
  rule_text   text not null,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now()
);

-- --------------------------------------------------------- protocol items

-- Your checklists. "category" says which list an item belongs to. The morning
-- brief reads the ones marked trading_open.
create table if not exists public.protocol_items (
  id          bigint generated by default as identity primary key,
  category    text not null default 'trading_open',
  sort_order  integer not null,
  item_text   text not null,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now()
);

-- ------------------------------------------------------------------ tasks

create table if not exists public.tasks (
  id              bigint generated by default as identity primary key,
  project_id      bigint references public.projects(id) on delete set null,
  title           text not null,
  detail          text,
  status          text not null default 'open'
                  check (status in ('open', 'done', 'dropped')),
  due_on          date,
  postpone_count  integer not null default 0,
  created_at      timestamptz not null default now(),
  completed_at    timestamptz
);

-- --------------------------------------------------------------- thoughts

-- Whatever you send the bot during the day, saved word for word.
--
-- is_private is load bearing. If AI is ever switched on, the check for it goes
-- in BEFORE the outbound request, never after.
create table if not exists public.thoughts (
  id            bigint generated by default as identity primary key,
  body          text not null,
  tags          text[] not null default '{}',
  is_private    boolean not null default false,
  ai_processed  boolean not null default false,
  source        text not null default 'telegram',
  created_at    timestamptz not null default now()
);

-- ---------------------------------------------------------- daily reviews

-- One row per day. raw_answer is exactly what you typed, unparsed.
create table if not exists public.daily_reviews (
  id            bigint generated by default as identity primary key,
  review_date   date not null unique,
  raw_answer    text not null,
  ai_processed  boolean not null default false,
  created_at    timestamptz not null default now()
);

-- ------------------------------------------------- lock every one of them

-- Row Level Security ON, and deliberately NO policies on any table.
--
-- That combination means the public key can read and write nothing at all.
-- Only server-side code holding the private key gets in. If something cannot
-- read the database, it is holding the wrong key. The answer is never to add a
-- policy here to "make it work".

alter table public.app_settings    enable row level security;
alter table public.goals           enable row level security;
alter table public.projects        enable row level security;
alter table public.roadmap_steps   enable row level security;
alter table public.trading_rules   enable row level security;
alter table public.protocol_items  enable row level security;
alter table public.tasks           enable row level security;
alter table public.thoughts        enable row level security;
alter table public.daily_reviews   enable row level security;

commit;

-- Tell the layer that sits in front of the database to notice the new tables.
-- Without this it can keep answering "no such table" for a while.
notify pgrst, 'reload schema';
